name: amar_recipe_user_app
description: Premium Bangladeshi and world recipe app
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
